// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Protoreg")]
[assembly: AssemblyDescriptionAttribute("Elders.Protoreg")]
[assembly: AssemblyProductAttribute("Elders.Protoreg")]
[assembly: AssemblyVersionAttribute("1.0.11")]
[assembly: AssemblyInformationalVersionAttribute("1.0.11")]
[assembly: AssemblyFileVersionAttribute("1.0.11")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.11";
    }
}
